'use client'
import Link from 'next/link'

const UI = "'Orbitron',sans-serif"

export default function TermsPage() {
  return <main className="min-h-screen" style={{background:'#000308',color:'#F0F0FF'}}>
    <div className="max-w-3xl mx-auto px-6 py-16">
      <Link href="/" style={{fontFamily:UI,fontSize:9,letterSpacing:'.2em',color:'rgba(0,229,255,.5)',textDecoration:'none',display:'inline-block',marginBottom:32}}>← SOVREND</Link>
      <h1 style={{fontFamily:UI,fontSize:24,fontWeight:700,letterSpacing:'.08em',marginBottom:8}}>Terms of Service</h1>
      <p style={{fontSize:12,color:'rgba(195,200,215,.45)',marginBottom:40}}>Last updated: March 26, 2026</p>

      <div style={{fontSize:14,lineHeight:1.9,color:'rgba(195,200,215,.75)'}}>
        <Section title="1. Acceptance">
          <p>By accessing or using SOVREND (&quot;the Service&quot;), you agree to these Terms. If you do not agree, do not use the Service. SOVREND is operated by SOVREND, Inc., a Delaware C-Corporation.</p>
        </Section>

        <Section title="2. The Service">
          <p>SOVREND is an AI-powered application builder. You provide natural language descriptions, and our AI generates React application code. The Service includes app building, refining, previewing, and related tools.</p>
        </Section>

        <Section title="3. Accounts">
          <ul className="list-disc pl-6">
            <li>You must provide accurate information when creating an account</li>
            <li>You are responsible for maintaining the security of your account</li>
            <li>You must be at least 13 years old to use the Service</li>
            <li>One person or entity per account</li>
          </ul>
        </Section>

        <Section title="4. Ownership of Generated Code">
          <p><b style={{color:'#F0F0FF'}}>You own the code generated by SOVREND.</b> When you use the Service to generate application code, you retain full ownership and intellectual property rights to that output. You may use, modify, distribute, and commercialize your generated applications without restriction.</p>
          <p className="mt-2">You grant SOVREND a limited license to store and process your prompts and generated code solely for the purpose of providing the Service.</p>
        </Section>

        <Section title="5. Usage Limits & Plans">
          <p>The Service offers tiered usage plans with build limits and cost caps:</p>
          <ul className="list-disc pl-6 mt-2">
            <li><b style={{color:'#F0F0FF'}}>Free</b> — Limited builds per month for evaluation</li>
            <li><b style={{color:'#F0F0FF'}}>Builder</b> — Expanded builds and features for individuals</li>
            <li><b style={{color:'#F0F0FF'}}>Agency</b> — Higher limits for teams and agencies</li>
          </ul>
          <p className="mt-2">We reserve the right to modify plan limits with reasonable notice. Exceeding limits may result in temporary service restrictions.</p>
        </Section>

        <Section title="6. Payments">
          <p>Paid plans are billed monthly through Stripe. All fees are non-refundable except as required by law. You may cancel at any time; access continues through the end of the billing period.</p>
        </Section>

        <Section title="7. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 mt-2">
            <li>Use the Service for illegal purposes</li>
            <li>Generate malicious code, malware, or tools designed to harm</li>
            <li>Attempt to circumvent usage limits or security measures</li>
            <li>Resell or redistribute the Service itself</li>
            <li>Use automated means to access the Service beyond normal usage</li>
            <li>Violate any applicable laws or regulations</li>
          </ul>
        </Section>

        <Section title="8. AI Limitations">
          <p>AI-generated code is provided &quot;as-is.&quot; While we strive for quality, generated applications may contain bugs, security vulnerabilities, or errors. You are responsible for reviewing, testing, and securing any code before deploying it to production. SOVREND is not liable for issues arising from generated code.</p>
        </Section>

        <Section title="9. Availability">
          <p>We aim for high availability but do not guarantee uninterrupted service. The Service depends on third-party providers (Anthropic, Google, Supabase, Vercel) whose availability is outside our control. We may perform maintenance with reasonable notice.</p>
        </Section>

        <Section title="10. Termination">
          <p>We may suspend or terminate your account for violations of these Terms. You may delete your account at any time. Upon termination, your stored data will be deleted within 30 days.</p>
        </Section>

        <Section title="11. Limitation of Liability">
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SOVREND SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.</p>
        </Section>

        <Section title="12. Governing Law">
          <p>These Terms are governed by the laws of the State of Delaware, without regard to conflict of law principles.</p>
        </Section>

        <Section title="13. Changes">
          <p>We may update these Terms. Material changes will be communicated via email or in-app notice at least 14 days before taking effect. Continued use after changes constitutes acceptance.</p>
        </Section>

        <Section title="14. Contact">
          <p>Questions about these terms: <a href="mailto:hello@sovrend.com" style={{color:'#00E5FF'}}>hello@sovrend.com</a></p>
          <p className="mt-2">SOVREND, Inc.<br/>A Delaware C-Corporation</p>
        </Section>
      </div>

      <div className="flex gap-4 mt-16 pt-8" style={{borderTop:'1px solid rgba(0,229,255,.07)'}}>
        <Link href="/privacy" style={{fontSize:12,color:'rgba(0,229,255,.5)',textDecoration:'none'}}>Privacy Policy</Link>
        <Link href="/" style={{fontSize:12,color:'rgba(0,229,255,.5)',textDecoration:'none'}}>Home</Link>
      </div>
    </div>
  </main>
}

function Section({title,children}:{title:string;children:React.ReactNode}) {
  return <div className="mb-8">
    <h2 style={{fontFamily:"'Orbitron',sans-serif",fontSize:11,letterSpacing:'.15em',color:'#00E5FF',marginBottom:12}}>{title}</h2>
    {children}
  </div>
}
